server: #can be removed when hosted on a server, this is to prevent conflicts when running on localhost
  port: 8090

#security:
#  user:
#    password: user
#  ignored: /,/favicon.ico,/index.html
#  sessions: ALWAYS
#  oauth2:
#    sso:
#      loginPath: /login
#management:
#  security:
#    role: HERO

logging:
  level:
    org.springframework.security: DEBUG
    com.netflix.discovery: 'OFF'

import: #delete or set to false if you don't want a fresh import from the employee services
  users: false
  kudos: true
  teams: true
  assessments: true

spring:
  profiles: default
security:
  oauth2:
    client:
      accessTokenUri: http://172.17.30.21:9999/uaa/oauth/token
      userAuthorizationUri: http://172.17.30.21:9999/uaa/oauth/authorize
      clientId: acme
      clientSecret: acmesecret
    resource:
      jwt:
        keyValue: |
          -----BEGIN PUBLIC KEY-----
          MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAnGp/Q5lh0P8nPL21oMMrt2RrkT9AW5jgYwLfSUnJVc9G6uR3cXRRDCjHqWU5WYwivcF180A6CWp/ireQFFBNowgc5XaA0kPpzEtgsA5YsNX7iSnUibB004iBTfU9hZ2Rbsc8cWqynT0RyN4TP1RYVSeVKvMQk4GT1r7JCEC+TNu1ELmbNwMQyzKjsfBXyIOCFU/E94ktvsTZUHF4Oq44DBylCDsS1k7/sfZC2G5EU7Oz0mhG8+Uz6MSEQHtoIi6mc8u64Rwi3Z3tscuWG2ShtsUFuNSAFNkY7LkLn+/hxLCu2bNISMaESa8dG22CIMuIeRLVcAmEWEWH5EEforTg+QIDAQAB
          -----END PUBLIC KEY-----
      id: openid
      serviceId: ${PREFIX:}resource

